language: node_js
sudo: false
node_js:
    - "stable"
cache:
    directories:
        - "$HOME/.npm"
install:
    - "npm ci"
script:
    - "npm run lint"
before_deploy:
    - "npm run build"
    - "tar -czf clash-$TRAVIS_TAG.tar.gz dist"
deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: clash-$TRAVIS_TAG.tar.gz
    skip_cleanup: true
    on:
        repo: blackhuman/clash-dashboard
        branch: dev
